energy_meters:
  name: Energy Meters
  entities:
    - sensor.total_power_consumption
    - sensor.total_power_production
    - sensor.consumption_low_tarif
    - sensor.consumption_high_tarif
    - sensor.production_low_tarif
    - sensor.production_high_tarif
    - sensor.gas
    # - sensor.water

actual_energy:
  name: Actual Energy
  entities:
    - sensor.tarif
    - sensor.actual_voltage_l1
    - sensor.actual_current_l1
    # - sensor.actual_power_consumption_2
    # - sensor.actual_power_production_2

UPS_Battery_energy:
  name: Battery energy
  entities:
    - switch.reset_battery
    - sensor.battery_status
    - sensor.battery_in_use
    - sensor.battery_charge
    - sensor.battery_is_charging
