version: '3'
services:
  # HomeAssistant
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      # Local path where your home assistant config will be stored
      - homeassistant:/config
      - ./home-assistant/configuration.yaml:/config/configuration.yaml
    ports:
      - "8123:8123"
    restart: unless-stopped
    privileged: true
    depends_on:
      - mosquitto
      - node-red

  # Mosquitto
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto:/mosquitto/config
      - mosquitto:/data:/mosquitto/data
      - mosquitto:/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  # Node-RED
  node-red:
    container_name: nodered
    image: nodered/node-red
    volumes:
      - nodered:/data
    ports:
      - "1880:1880"
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "Europe/Brussels"
    restart: unless-stopped

volumes:
  homeassistant:
  mosquitto:
  nodered:
