version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant"
    volumes:
      - ./homeassistant/config:/config
    restart: unless-stopped
    depends_on:
      - mosquitto
    ports:
      - 8123:8123

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto/:/mosquitto/config/:ro
      - mosquitto:/mosquitto/log/
      - ./mosquitto/data/:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
      
  # node-red:
  #   container_name: node-red
  #   image: nodered/node-red:latest
  #   environment:
  #     - TZ=Europe/Amsterdam
  #   ports:
  #     - "1880:1880"
  #   volumes:
  #     - project-exp:/node-red-data:/data    

volumes:
  homeassistant:
  mosquitto:
    