homeassistant:
default_config:

mqtt:
  sensor:
    - name: "Consumption low tarif"
      unit_of_measurement: 'kWh'
      state_topic: "homeassistant/battery/payload"
      unique_id: "consumption_low_tarif"
      value_template: "{{ value|float  }}"
      
  text:
    - name: "test mqtt test"
      command_topic: "homeassistant/battery/state"
      retain: true
      state_topic: "homeassistant/battery/state"
      unique_id: "test mqtt"
      min: 1
      max: 255

# # Group can't be done because of the text entity and the sensor entity are not of the same type
# mqtt-group:
#   name: test mqtt current
#   entities:
#     - text.test_mqtt_test
#     - sensor.consumption_low_tarif
