sensor:
  # battery status
  - name: "battery status"
    unique_id: "battery_status"
    device_class: energy
    state_topic: "homeassistant/battery/Status"
    value_template: "{{ value|bool}}"

  # battery in use
  - name: "battery in use"
    unique_id: "battery_in_use"
    device_class: energy
    state_topic: "homeassistant/battery/InUse"
    value_template: "{{ value|bool  }}"

  # battery charge
  - name: "battery charge"
    unique_id: "battery_charge"
    device_class: energy
    state_topic: "homeassistant/battery/Charge"
    value_template: "{{ value|float /100}}"
    unit_of_measurement: "%"

switch:
  # reset battery when on
  - name: "reset battery"
    unique_id: "reset_battery"
    entity_category: "config"
    retain: false
    qos: 0
    command_topic: "homeassistant/battery/reset"
    payload_on: "reset"
    payload_off: "ok"

sensor:
  # total power consumption
  - name: "total power consumption"
    unique_id: "total_power_consumption"
    device_class: "energy"
    state_class: "total"
    state_topic: "smartmeter/total_power_consumption"
    value_template: "{{ value | float}}"
    unit_of_measurement: "kWh"
    # last_reset_topic: "smartmeter/total_power_consumption"
    # last_reset_value_template: "1970-01-01T00:00:00+00:00"

  # total power production
  - name: "total power production"
    unique_id: "total_power_production"
    device_class: "energy"
    state_class: "total"
    state_topic: "smartmeter/total_power_production"
    value_template: "{{ value|float}}"
    unit_of_measurement: "kWh"
    # last_reset_topic: "smartmeter/total_power_production"
    # last_reset_value_template: '1970-01-01T00:00:00+00:00'

  # consumption low tarif
  - name: consumption low tarif
    unique_id: "consumption_low_tarif"
    device_class: energy
    state_class: total
    state_topic: "smartmeter/consumption_low_tarif"
    value_template: "{{ value|float }}"
    unit_of_measurement: "kWh"

  # consumption high tarif
  - name: consumption high tarif
    unique_id: "consumption_high_tarif"
    device_class: energy
    state_class: total
    state_topic: "smartmeter/consumption_high_tarif"
    value_template: "{{ value|float }}"
    unit_of_measurement: "kWh"

  # production low tarif
  - name: production low tarif
    unique_id: "production_low_tarif"
    device_class: energy
    state_class: total
    state_topic: "smartmeter/production_low_tarif"
    value_template: "{{ value|float }}"
    unit_of_measurement: "kWh"

  # production high tarif
  - name: production high tarif
    unique_id: "production_high_tarif"
    device_class: energy
    state_class: total
    state_topic: "smartmeter/production_high_tarif"
    value_template: "{{ value|float }}"
    unit_of_measurement: "kWh"