services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant"
    volumes:
      - homeassistant-config:/config
    restart: unless-stopped
    privileged: true
    depends_on:
      - mosquitto
    ports:
      - 8123:8123

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
      
volumes:
  homeassistant-config:
  mosquitto-data:
  mosquitto-log:
    