blueprint:
  name: Create Group
  description: Creates a group of entities
  domain: automation
  input:
    group_name:
      name: 'Name to assign to the group. Example: All Lights'
      default: 'Battery Energy'
    group_object_id:
      name: 'object_id to assign to the group. Example: all_lights'
      default: 'Battery_Energy'

    Battery_filter:
      name: Battery Filter
      description: The entity filter used to include sensors in the group
      default: 
        entity_id: 
        - sensor.battery_charge
        - sensor.battery_status
        - sensor.battery_in_use
        - sensor.battery_is_charging
        - switch.reset_battery
        domain: sensor
      selector:
        target:
          entity: {}

mode: single
trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: group
      service: group.reload
 
action: